import { Header } from "@/components/layout/Header";
import "./globals.css";
import { ContextProvider } from "@/lib/context/ContextProvider";
import SessionWrapper from "@/lib/auth/SessionWrapper";
import { Container } from "@/components/layout/Container";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
        >
          <ContextProvider>
            <Container>
              <Header />
              {children}
            </Container>
          </ContextProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
